name: SonarQube Quality Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Permite un análisis más completo de Git en Sonar

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        working-directory: ucv-ate-si-laboratorio08
        run: poetry install

      - name: Run Tests with Coverage
        working-directory: ucv-ate-si-laboratorio08
        run: |
          poetry run pytest --cov=agente_ucv --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ucv-ate-si-laboratorio08
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}